name: Auto update README

on:
  push:
    branches: [ main ]

jobs:
  update-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set date variable
        run: echo "DATE=$(date '+%Y.%m.%d')" >> $GITHUB_ENV

      - name: Replace last updated in README
        run: |
          sed -i -E "s/手順確認日-[0-9]{4}\.[0-9]{2}\.[0-9]{2}/手順確認日-${DATE}/" README.md

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          if ! git diff --cached --quiet; then
            git commit -m "chore: update README last updated to ${DATE}"
            git push
          fi
